### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by MazenSenih** [hajduakos/PanoDotNet#1]
Hi there, this is great,
I'm not familiar with wpf, what do I need to add/change to view the image in highest quality?!
thanks in advance.

**Comment by hajduakos** [comment]
Hi! Thanks!

So basically I just open the image and set it as the source of an `ImageBrush`, which is then used to fill the inner side of a sphere. So the resolution/quality of the image should be as good as the original image.

However, I observed that there are certain resolutions that look very bad (big pixels), but if I resize the image just a little bit, it looks nice. For example a 14634x7317 image looks bad, but resizing it to 14600x7300 or 14640x7320 is perfectly fine.

I have absolutely no clue why this happens. Maybe it has to do something with divisibility: as you can see in line 56 of `PanoView.xaml.cs`, the sphere is tessellated into a 40x20 mesh, so maybe if the resolution is divisible by 40 and 20 then it is fine and otherwise it is bad.

Let me know if this resizing works for you, or you can also send me the picture that you tried and I can have a look at it.

**Comment by MazenSenih** [comment]
Hi!, yeah It works fine when displaying HQ images.
